openalerts/management/urls.py
from django.urls import path
from .views import (
    DashboardView,
    OrganizationView,
    EditOrganizationView,
    LoginView,
    LogoutView,
    ChannelListView,
    ChannelView,
    CreateChannelView,
    EditChannelView,
    CreateAlertView,
    EditAlertView,
    DeleteAlertView,
    DeleteChannelView,
    SourceListView,
    DeleteSourceView,
    CreateSourceView,
    OrganizationIntegrationsView,
    SubscriberTableView,
    SubscriberEmailExportView
)

app_name = "management"

urlpatterns = [
    path("", DashboardView.as_view(), name="dashboard"),
    path(
        "organization/<int:org_id>/",
        OrganizationView.as_view(extra_context={"tab_scope": "overview"}),
        name="organization",
    ),
    path(
        "organization/<int:org_id>/integrations/",
        OrganizationIntegrationsView.as_view(extra_context={"tab_scope": "overview"}),
        name="integrations",
    ),
    path(
        "organization/<int:org_id>/edit/",
        EditOrganizationView.as_view(extra_context={"tab_scope": "overview"}),
        name="edit_organization",
    ),
    path(
        "organization/<int:org_id>/channels/",
        ChannelListView.as_view(extra_context={"tab_scope": "channels"}),
        name="channel_list",
    ),
    path(
        "organization/<int:org_id>/channels/create/",
        CreateChannelView.as_view(extra_context={"tab_scope": "channels"}),
        name="create_channel",
    ),
    path(
        "organization/<int:org_id>/channels/<int:pk>/",
        ChannelView.as_view(extra_context={"tab_scope": "channels"}),
        name="channel",
    ),
    path(
        "organization/<int:org_id>/channels/<int:pk>/edit/",
        EditChannelView.as_view(extra_context={"tab_scope": "channels"}),
        name="edit_channel",
    ),
    path(
        "organization/<int:org_id>/channels/<int:pk>/delete/",
        DeleteChannelView.as_view(extra_context={"tab_scope": "channels"}),
        name="delete_channel",
    ),
    path(
        "organization/<int:org_id>/channels/<int:channel_id>/sources/",
        SourceListView.as_view(extra_context={"tab_scope": "channels"}),
        name="source_list"
    ),
    path(
        "organization/<int:org_id>/channels/<int:channel_id>/sources/create/",
        CreateSourceView.as_view(extra_context={"tab_scope": "channels"}),
        name="create_source"
    ),
    path(
        "organization/<int:org_id>/channels/<int:channel_id>/sources/<int:pk>/delete/",
        DeleteSourceView.as_view(extra_context={"tab_scope": "channels"}),
        name="delete_source"
    ),
    path(
        "organization/<int:org_id>/alert/publish/",
        CreateAlertView.as_view(extra_context={"tab_scope": "publish"}),
        name="create_alert",
    ),
    path(
        "organization/<int:org_id>/alert/<int:pk>/edit/",
        EditAlertView.as_view(extra_context={"tab_scope": "publish"}),
        name="edit_alert",
    ),
    path(
        "organization/<int:org_id>/alert/<int:pk>/delete/",
        DeleteAlertView.as_view(extra_context={"tab_scope": "publish"}),
        name="delete_alert",
    ),
    path(
        "organization/<int:org_id>/subscribers/",
        SubscriberTableView.as_view(extra_context={"tab_scope": "subscribers"}),
        name="subscribers"
    ),
    path(
        "organization/<int:org_id>/subscribers/export/",
        SubscriberEmailExportView.as_view(extra_context={"tab_scope": "subscribers"}),
        name="subscribers_email_export"
    ),
    path("login/", LoginView.as_view(), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
]

openalerts/openalerts/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('webpush/', include('webpush.urls')),

    # LOCAL
    path('management/', include("management.urls", namespace='management')),
    path('auth/', include('social_django.urls', namespace='auth')),
    path('rss/', include('rss.urls', namespace='rss')),
    path('', include('public.urls', namespace='public'))
]

openalerts/rss/urls.py
from django.urls import path
from .views import ChannelFeed, OrganizationFeed

app_name = "rss"

urlpatterns = [
    path("<int:org_id>/<str:slug>/", ChannelFeed(), name="channel_feed"),
    path("<int:org_id>/", OrganizationFeed(), name="organization_feed"),
]

openalerts/management/views/alert.py
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from management.mixins import SessionAuthenticationRequiredMixin, SessionOrgContextMixin, OrgContextMixin
from django.urls import reverse
from django import forms
from management.models import Organization
from alerts.models import Channel, Alert

class CreateAlertView(SessionAuthenticationRequiredMixin, SessionOrgContextMixin, OrgContextMixin, CreateView):
    template_name = "management/pages/edit_alert.html"
    model = Alert
    fields = ["channel", "content", "url"]

    def get_form(self, *args, **kwargs):
        form = super(CreateAlertView, self).get_form(*args, **kwargs)
        form.fields['channel'].queryset = Channel.objects.filter(organization__id=self.kwargs["org_id"])
        return form

    def get_initial(self):
        initial = super().get_initial()
        if self.request.GET.get("channel", None) != None:
            initial["channel"] = int(self.request.GET.get("channel"))
        return initial

    def get_success_url(self):
        return reverse("management:channel", kwargs={"org_id": self.object.channel.organization.pk, "pk": self.object.channel.pk})

class EditAlertView(SessionAuthenticationRequiredMixin, SessionOrgContextMixin, OrgContextMixin, UpdateView):
    template_name = "management/pages/edit_alert.html"
    model = Alert
    fields = ["url"]
    edit = True # indicates to the template that this is an editing context

    def get_success_url(self):
        return reverse("management:channel", kwargs={"org_id": self.object.channel.organization.pk, "pk": self.object.channel.pk})

class DeleteAlertView(SessionAuthenticationRequiredMixin, SessionOrgContextMixin, OrgContextMixin, DeleteView):
    template_name = "management/pages/delete_alert.html"
    model = Alert

    def get_success_url(self):
        return reverse("management:channel", kwargs={"org_id": self.object.channel.organization.pk, "pk": self.object.channel.pk})

openalerts/management/views/channels.py
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic.base import ContextMixin
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.core.paginator import Paginator
from management.mixins import SessionAuthenticationRequiredMixin, SessionOrgContextMixin, OrgContextMixin
from management.models import Organization
from alerts.models import Channel, Alert
from django.utils.http import urlencode

class ChannelListView(
    SessionAuthenticationRequiredMixin, SessionOrgContextMixin, DetailView
):
    template_name = "management/pages/channel_list.html"
    model = Organization
    pk_url_kwarg = "org_id"

class CreateChannelView(
    SessionAuthenticationRequiredMixin, SessionOrgContextMixin, OrgContextMixin, CreateView
):
    template_name = "management/pages/edit_channel.html"
    model = Channel
    fields = ["name", "description"]

    def form_valid(self, form):
        form.instance.organization = self.get_context_data()["organization"]
        return super(CreateChannelView, self).form_valid(form)

    def get_success_url(self, **kwargs):
        return reverse_lazy("management:channel", kwargs={"org_id": self.kwargs["org_id"], "pk": self.object.id})

class EditChannelView(
    SessionAuthenticationRequiredMixin, SessionOrgContextMixin, OrgContextMixin, UpdateView
):
    template_name = "management/pages/edit_channel.html"
    model = Channel
    fields = ["name", "description"]

    def get_success_url(self, **kwargs):
        return reverse_lazy("management:channel", kwargs={"org_id": self.kwargs["org_id"], "pk": self.object.id})

class DeleteChannelView(
    SessionAuthenticationRequiredMixin, SessionOrgContextMixin, OrgContextMixin, DeleteView
):
    template_name = "management/pages/delete_channel.html"
    model = Channel

    def get_success_url(self, **kwargs):
        return reverse_lazy("management:channel_list", kwargs={"org_id": self.kwargs["org_id"]})

class ChannelView(
    SessionAuthenticationRequiredMixin, SessionOrgContextMixin, OrgContextMixin, DetailView
):
    template_name = "management/pages/channel.html"
    model = Channel

    def get_context_data(self, **kwargs):
        search = self.request.GET.get("search", None)
        objects = self.object.alerts
        if search:
            objects = self.object.alerts.filter(content__icontains=search)
        else:
            search = ""
        paginator = Paginator(objects, 15)
        page_obj = paginator.get_page(self.request.GET.get("page", 1))
        context = super(ChannelView, self).get_context_data(**kwargs)
        context.update(dict(page_obj=page_obj, paginator=paginator, total_alerts=objects.count(), url_parameters=urlencode([("search", search)])))
        return context

openalerts/management/views/dashboard.py
from django.views.generic import TemplateView
from management.mixins import SessionAuthenticationRequiredMixin, SessionOrgContextMixin
from django.shortcuts import redirect
from management.models import Organization

class DashboardView(SessionAuthenticationRequiredMixin, SessionOrgContextMixin, TemplateView):
    template_name = "management/pages/dashboard.html"

    def dispatch(self, *args, **kwargs):
        if len(self.get_context_data().get("organizations")) == 1:
            return redirect("management:organization", self.get_context_data().get("organizations")[0].id)
        return super(DashboardView, self).dispatch(*args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context

openalerts/management/views/organization.py
from django.views.generic.edit import UpdateView
from django.views.generic.detail import DetailView
from django.shortcuts import get_object_or_404, reverse
from django.utils import timezone
from django.conf import settings
from datetime import timedelta, datetime
from django import forms
from management.mixins import SessionAuthenticationRequiredMixin, SessionOrgContextMixin, OrgContextMixin
from management.models import Organization
from subscriptions.models import WebpushSubscription, EmailSubscription


class EditOrganizationView(
    SessionAuthenticationRequiredMixin, SessionOrgContextMixin, UpdateView
):
    template_name = "management/pages/edit_organization.html"
    model = Organization
    fields = ["name", "website", "description", "logo_url", "primary_color", "head_inject"]
    pk_url_kwarg = "org_id"

    def get_form(self, *args, **kwargs):
        form = super(EditOrganizationView, self).get_form(*args, **kwargs)
        form["primary_color"].field.widget.input_type = "color"
        return form
    
    def get_object(self):
        return get_object_or_404(Organization, id=self.kwargs["org_id"])

    def get_success_url(self):
        print(self.object.id)
        return reverse("management:organization", args=[self.object.id])

class OrganizationView(
    SessionAuthenticationRequiredMixin, SessionOrgContextMixin, DetailView
):
    template_name = "management/pages/organization.html"
    model = Organization
    pk_url_kwarg = "org_id"

    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)

        email_subscribers = EmailSubscription.objects.filter(organization=self.object)
        webpush_subscribers = WebpushSubscription.objects.filter(organization=self.object)

        data["subscribers"] = {
            "keys": str(["Email", "Web Alerts"]),
            "values": str([email_subscribers.count(),
                           webpush_subscribers.count()]),
            "count": email_subscribers.count() + webpush_subscribers.count(),
        }

        data["recent_alerts_count"] = self.object.alerts().filter(published__gt=timezone.now() - timedelta(days=1)).count()

        subscribers = list(email_subscribers) + list(webpush_subscribers)
        times = reversed([timezone.now() - timedelta(n) for n in range(90)]) # last 90 days

        data["subscribers_timeseries"] = {
            "label": "Currently Active Subscribers",
            "values": str([{
                "t": time.isoformat(),
                "y": len([subscription for subscription in subscribers if subscription.created <= time])
                # Deleted subscribers will not be shown in the chart, hence "current"
            } for time in times])
        }

        data["protocol_and_host"] = settings.PROTOCOL_AND_HOST

        return data

class OrganizationIntegrationsView(SessionAuthenticationRequiredMixin, SessionOrgContextMixin, DetailView):
    template_name = "management/pages/integrations.html"
    model = Organization
    pk_url_kwarg = "org_id"

    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)
        data["protocol_and_host"] = settings.PROTOCOL_AND_HOST
        return data

openalerts/management/views/sources.py
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic.base import ContextMixin
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django import forms
from django.core.paginator import Paginator
from management.mixins import (
    SessionAuthenticationRequiredMixin,
    SessionOrgContextMixin,
    OrgContextMixin,
)
from management.models import Organization
from alerts.models import Source, Channel


class SourceListView(
    SessionAuthenticationRequiredMixin, SessionOrgContextMixin, OrgContextMixin, DetailView
):
    template_name = "management/pages/source_list.html"
    model = Channel
    pk_url_kwarg = "channel_id"


class CreateSourceView(
    SessionAuthenticationRequiredMixin,
    SessionOrgContextMixin,
    OrgContextMixin,
    CreateView,
):
    template_name = "management/pages/edit_source.html"
    model = Source
    fields = ["source", "human_readable_identifier"]

    def get_form(self, *args, **kwargs):
        form = super(CreateSourceView, self).get_form(*args, **kwargs)
        form.fields['human_readable_identifier'].label = "Username or handle"
        form.fields['human_readable_identifier'].widget = forms.TextInput()
        return form

    def get_context_data(self, **kwargs):
        context = super(CreateSourceView, self).get_context_data(**kwargs)
        context.update(dict(channel=Channel.objects.get(id=self.kwargs["channel_id"])))
        return context

    def form_valid(self, form):
        form.instance.channel = self.get_context_data()["channel"]
        return super(CreateSourceView, self).form_valid(form)

    def get_success_url(self, **kwargs):
        return reverse_lazy(
            "management:source_list",
            kwargs={
                "org_id": self.kwargs["org_id"],
                "channel_id": self.object.channel.id,
            },
        )


class DeleteSourceView(
    SessionAuthenticationRequiredMixin,
    SessionOrgContextMixin,
    OrgContextMixin,
    DeleteView,
):
    template_name = "management/pages/delete_source.html"
    model = Source

    def get_success_url(self, **kwargs):
        return reverse_lazy(
            "management:source_list",
            kwargs={
                "org_id": self.kwargs["org_id"],
                "channel_id": self.kwargs["channel_id"],
            },
        )

openalerts/management/views/subscribers.py
from django.shortcuts import get_object_or_404, reverse
from django.views.generic import TemplateView, View
from django.conf import settings
from datetime import timedelta, datetime
from django import forms
from django.http import HttpResponse
import io
import unicodecsv as csv
from management.mixins import (
    SessionAuthenticationRequiredMixin,
    SessionOrgContextMixin,
    OrgContextMixin,
)
from management.models import Organization
from subscriptions.models import WebpushSubscription, EmailSubscription


class SubscriberTableView(
    SessionAuthenticationRequiredMixin, OrgContextMixin, TemplateView
):
    template_name = "management/pages/subscribers.html"

    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)
        data["email_subscribers"] = EmailSubscription.objects.filter(
            organization=data["organization"]
        )
        data["webpush_subscribers"] = WebpushSubscription.objects.filter(
            organization=data["organization"]
        )
        return data


class SubscriberEmailExportView(
    SessionAuthenticationRequiredMixin, OrgContextMixin, View
):
    def get(self, request, *args, **kwargs):
        org = request.organization

        outfile = io.BytesIO()
        writer = csv.DictWriter(
            outfile, fieldnames=["email", "verified", "created", "channels"]
        )
        writer.writeheader()
        writer.writerows(
            [
                {
                    "email": sub.email,
                    "verified": sub.verified,
                    "created": sub.created,
                    "channels": ", ".join(
                        [channel.name for channel in sub.channels.all()]
                    ),
                }
                for sub in EmailSubscription.objects.filter(organization=org)
            ]
        )

        response = HttpResponse(outfile.getvalue(), content_type="text/csv")
        response["Content-Disposition"] = 'attachment; filename="OA_EmailExport.csv"'
        return response

openalerts/management/templates/management/base.html
{% load static %}

<!DOCTYPE html>
<html>

<head>
    <title>{{title|default:"Management"}} | OpenAlerts Management</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.8.0/css/bulma.min.css"
        integrity="sha256-D9M5yrVDqFlla7nlELDaYZIpXfFWDytQtiV+TaH6F1I=" crossorigin="anonymous">
    <script src="{% static 'management/js/navbar.js' %}"></script>
    <link rel="stylesheet" href="{% static 'management/css/management.css' %}">
</head>

<body>
    <nav class="navbar is-link" role="navigation" aria-label="main navigation">
        <div class="container">
            <div class="navbar-brand">
                <a class="navbar-item" href="{% url 'management:dashboard' %}">
                    <strong>Open Alerts</strong>
                </a>

                <a role="button" class="navbar-burger burger" aria-label="menu" aria-expanded="false"
                    data-target="topNavbar">
                    <span aria-hidden="true"></span>
                    <span aria-hidden="true"></span>
                    <span aria-hidden="true"></span>
                </a>
            </div>

            <div id="topNavbar" class="navbar-menu">
                <div class="navbar-end">
                    {% if request.session.presspass_authenticated %}
                    <div class="navbar-item has-dropdown is-hoverable">
                        <a class="navbar-link">
                            Organizations
                        </a>

                        <div class="navbar-dropdown">
                            {% for organization in organizations %}
                            <a href="{% url 'management:organization' organization.id %}"
                                class="navbar-item">{{organization.name}}</a>
                            {% endfor %}
                        </div>
                    </div>
                    <a href="{% url 'management:logout' %}" class="navbar-item">Log Out</a>
                    {% else %}
                    <div class="navbar-item">
                        <a href="{% url 'management:login' %}" class="button is-light is-outlined">Log In</a>
                    </div>
                    {% endif %}
                </div>
            </div>
        </div>
    </nav>
    {% block precontent %}
    {% endblock %}
    <section class="section">
        <div class="container">
            {% block content %}
            {% endblock %}
            <hr>
            <p class="has-text-grey">OpenAlerts is an <a href="https://github.com/news-catalyst/openalerts">open-source</a> public benefit project by <a href="https://newscatalyst.org">News Catalyst</a> offered through PressPass.</p> 
        </div>
    </section>
</body>

</html>

openalerts/management/templates/management/organization_base.html
{% extends 'management/base.html' %}

{% block precontent %}
<section class="hero is-link is-org-hero">
    <div class="hero-body">
        <div class="container">
            <div class="level">
                <div class="level-left">
                    <div class="level-item is-block">
                        <p class="heading">Managing</p>
                        <h1 class="title is-capitalized is-size-3">
                            <a href="{% url 'management:organization' org_id=organization.id %}" class="always-white">{{organization.name}}</a>
                            <span class="has-text-weight-light">
                                {% block subsection %}
                                {% endblock %}
                            </span>
                        </h1>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="hero-foot">
        <div class="container">
            <div class="tabs is-boxed">
                <ul>
                    <li {% if tab_scope == "overview" %}class="is-active" {% endif %}><a
                            href="{% url 'management:organization' org_id=organization.id %}">Overview</a></li>
                    <li {% if tab_scope == "channels" %}class="is-active" {% endif %}><a
                            href="{% url 'management:channel_list' org_id=organization.id %}">Channels</a></li>
                    <li {% if tab_scope == "publish" %}class="is-active" {% endif %}><a
                        href="{% url 'management:create_alert' org_id=organization.id %}">Publish</a></li>
                    <li {% if tab_scope == "subscribers" %}class="is-active" {% endif %}><a
                        href="{% url 'management:subscribers' org_id=organization.id %}">Subscribers</a></li>
                    <li><a
                        href="{% url 'public:index' %}?org={{organization.id}}">Public View</a></li>
                </ul>
            </div>
        </div>
    </div>
</section>
<div class="actions-container">
    <div class="container">
        <div class="org-page-action">{% block action %}{% endblock %}</div>
    </div>
</div>
{% endblock %}
{% block content %}
{% endblock %}