openalerts/management/urls.py
from django.urls import path
from .views import (
    DashboardView,
    OrganizationView,
    EditOrganizationView,
    LoginView,
    LogoutView,
    ChannelListView,
    ChannelView,
    CreateChannelView,
    EditChannelView,
    CreateAlertView,
    EditAlertView,
    DeleteAlertView,
    DeleteChannelView,
    SourceListView,
    DeleteSourceView,
    CreateSourceView,
    OrganizationIntegrationsView,
    SubscriberTableView,
    SubscriberEmailExportView
)

app_name = "management"

urlpatterns = [
    path("", DashboardView.as_view(), name="dashboard"),
    path(
        "organization/<int:org_id>/",
        OrganizationView.as_view(extra_context={"tab_scope": "overview"}),
        name="organization",
    ),
    path(
        "organization/<int:org_id>/integrations/",
        OrganizationIntegrationsView.as_view(extra_context={"tab_scope": "overview"}),
        name="integrations",
    ),
    path(
        "organization/<int:org_id>/edit/",
        EditOrganizationView.as_view(extra_context={"tab_scope": "overview"}),
        name="edit_organization",
    ),
    path(
        "organization/<int:org_id>/channels/",
        ChannelListView.as_view(extra_context={"tab_scope": "channels"}),
        name="channel_list",
    ),
    path(
        "organization/<int:org_id>/channels/create/",
        CreateChannelView.as_view(extra_context={"tab_scope": "channels"}),
        name="create_channel",
    ),
    path(
        "organization/<int:org_id>/channels/<int:pk>/",
        ChannelView.as_view(extra_context={"tab_scope": "channels"}),
        name="channel",
    ),
    path(
        "organization/<int:org_id>/channels/<int:pk>/edit/",
        EditChannelView.as_view(extra_context={"tab_scope": "channels"}),
        name="edit_channel",
    ),
    path(
        "organization/<int:org_id>/channels/<int:pk>/delete/",
        DeleteChannelView.as_view(extra_context={"tab_scope": "channels"}),
        name="delete_channel",
    ),
    path(
        "organization/<int:org_id>/channels/<int:channel_id>/sources/",
        SourceListView.as_view(extra_context={"tab_scope": "channels"}),
        name="source_list"
    ),
    path(
        "organization/<int:org_id>/channels/<int:channel_id>/sources/create/",
        CreateSourceView.as_view(extra_context={"tab_scope": "channels"}),
        name="create_source"
    ),
    path(
        "organization/<int:org_id>/channels/<int:channel_id>/sources/<int:pk>/delete/",
        DeleteSourceView.as_view(extra_context={"tab_scope": "channels"}),
        name="delete_source"
    ),
    path(
        "organization/<int:org_id>/alert/publish/",
        CreateAlertView.as_view(extra_context={"tab_scope": "publish"}),
        name="create_alert",
    ),
    path(
        "organization/<int:org_id>/alert/<int:pk>/edit/",
        EditAlertView.as_view(extra_context={"tab_scope": "publish"}),
        name="edit_alert",
    ),
    path(
        "organization/<int:org_id>/alert/<int:pk>/delete/",
        DeleteAlertView.as_view(extra_context={"tab_scope": "publish"}),
        name="delete_alert",
    ),
    path(
        "organization/<int:org_id>/subscribers/",
        SubscriberTableView.as_view(extra_context={"tab_scope": "subscribers"}),
        name="subscribers"
    ),
    path(
        "organization/<int:org_id>/subscribers/export/",
        SubscriberEmailExportView.as_view(extra_context={"tab_scope": "subscribers"}),
        name="subscribers_email_export"
    ),
    path("login/", LoginView.as_view(), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
]

openalerts/openalerts/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('webpush/', include('webpush.urls')),

    # LOCAL
    path('management/', include("management.urls", namespace='management')),
    path('auth/', include('social_django.urls', namespace='auth')),
    path('rss/', include('rss.urls', namespace='rss')),
    path('', include('public.urls', namespace='public'))
]

openalerts/rss/urls.py
from django.urls import path
from .views import ChannelFeed, OrganizationFeed

app_name = "rss"

urlpatterns = [
    path("<int:org_id>/<str:slug>/", ChannelFeed(), name="channel_feed"),
    path("<int:org_id>/", OrganizationFeed(), name="organization_feed"),
]

openalerts/alerts/models/channel.py
from django.db import models
from django.utils.text import slugify
from management.models import Organization

class Channel(models.Model):
    name = models.CharField(max_length=128)
    organization = models.ForeignKey(Organization, editable=False, on_delete=models.CASCADE)
    slug = models.SlugField(editable=False)
    description = models.TextField()

    class Meta:
        unique_together = [["slug", "organization"]]

    def save(self, *args, **kwargs):
        value = self.name
        self.slug = slugify(value, allow_unicode=False)
        super().save(*args, **kwargs)

    def __str__(self):
        return self.name

    @property
    def alerts(self):
        return self.alert_set.all().order_by("-published")

openalerts/alerts/models/source.py
from django.db import models
from .channel import Channel

class Source(models.Model):
    source = models.CharField(max_length=10, choices=[("TWITTER", "Twitter")])
    identifier = models.TextField(null=True, blank=True) # In the case of Twitter, the account's ID
    human_readable_identifier = models.TextField(blank=True, default="", help_text="On Twitter, for example, this is the account's @username.")
    channel = models.ForeignKey(Channel, on_delete=models.CASCADE)

    class Meta:
        unique_together = ("source", "identifier")

    def save(self, *args, **kwargs):
        if self.identifier != None and len(self.identifier.strip()) == 0:
            self.identifier = None
        super(Source, self).save(*args, **kwargs)

    def __str__(self):
        return self.human_readable_identifier

openalerts/management/views/alert.py
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from management.mixins import SessionAuthenticationRequiredMixin, SessionOrgContextMixin, OrgContextMixin
from django.urls import reverse
from django import forms
from management.models import Organization
from alerts.models import Channel, Alert

class CreateAlertView(SessionAuthenticationRequiredMixin, SessionOrgContextMixin, OrgContextMixin, CreateView):
    template_name = "management/pages/edit_alert.html"
    model = Alert
    fields = ["channel", "content", "url"]

    def get_form(self, *args, **kwargs):
        form = super(CreateAlertView, self).get_form(*args, **kwargs)
        form.fields['channel'].queryset = Channel.objects.filter(organization__id=self.kwargs["org_id"])
        return form

    def get_initial(self):
        initial = super().get_initial()
        if self.request.GET.get("channel", None) != None:
            initial["channel"] = int(self.request.GET.get("channel"))
        return initial

    def get_success_url(self):
        return reverse("management:channel", kwargs={"org_id": self.object.channel.organization.pk, "pk": self.object.channel.pk})

class EditAlertView(SessionAuthenticationRequiredMixin, SessionOrgContextMixin, OrgContextMixin, UpdateView):
    template_name = "management/pages/edit_alert.html"
    model = Alert
    fields = ["url"]
    edit = True # indicates to the template that this is an editing context

    def get_success_url(self):
        return reverse("management:channel", kwargs={"org_id": self.object.channel.organization.pk, "pk": self.object.channel.pk})

class DeleteAlertView(SessionAuthenticationRequiredMixin, SessionOrgContextMixin, OrgContextMixin, DeleteView):
    template_name = "management/pages/delete_alert.html"
    model = Alert

    def get_success_url(self):
        return reverse("management:channel", kwargs={"org_id": self.object.channel.organization.pk, "pk": self.object.channel.pk})

openalerts/management/views/channels.py
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic.base import ContextMixin
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.core.paginator import Paginator
from management.mixins import SessionAuthenticationRequiredMixin, SessionOrgContextMixin, OrgContextMixin
from management.models import Organization
from alerts.models import Channel, Alert
from django.utils.http import urlencode

class ChannelListView(
    SessionAuthenticationRequiredMixin, SessionOrgContextMixin, DetailView
):
    template_name = "management/pages/channel_list.html"
    model = Organization
    pk_url_kwarg = "org_id"

class CreateChannelView(
    SessionAuthenticationRequiredMixin, SessionOrgContextMixin, OrgContextMixin, CreateView
):
    template_name = "management/pages/edit_channel.html"
    model = Channel
    fields = ["name", "description"]

    def form_valid(self, form):
        form.instance.organization = self.get_context_data()["organization"]
        return super(CreateChannelView, self).form_valid(form)

    def get_success_url(self, **kwargs):
        return reverse_lazy("management:channel", kwargs={"org_id": self.kwargs["org_id"], "pk": self.object.id})

class EditChannelView(
    SessionAuthenticationRequiredMixin, SessionOrgContextMixin, OrgContextMixin, UpdateView
):
    template_name = "management/pages/edit_channel.html"
    model = Channel
    fields = ["name", "description"]

    def get_success_url(self, **kwargs):
        return reverse_lazy("management:channel", kwargs={"org_id": self.kwargs["org_id"], "pk": self.object.id})

class DeleteChannelView(
    SessionAuthenticationRequiredMixin, SessionOrgContextMixin, OrgContextMixin, DeleteView
):
    template_name = "management/pages/delete_channel.html"
    model = Channel

    def get_success_url(self, **kwargs):
        return reverse_lazy("management:channel_list", kwargs={"org_id": self.kwargs["org_id"]})

class ChannelView(
    SessionAuthenticationRequiredMixin, SessionOrgContextMixin, OrgContextMixin, DetailView
):
    template_name = "management/pages/channel.html"
    model = Channel

    def get_context_data(self, **kwargs):
        search = self.request.GET.get("search", None)
        objects = self.object.alerts
        if search:
            objects = self.object.alerts.filter(content__icontains=search)
        else:
            search = ""
        paginator = Paginator(objects, 15)
        page_obj = paginator.get_page(self.request.GET.get("page", 1))
        context = super(ChannelView, self).get_context_data(**kwargs)
        context.update(dict(page_obj=page_obj, paginator=paginator, total_alerts=objects.count(), url_parameters=urlencode([("search", search)])))
        return context

openalerts/management/views/dashboard.py
from django.views.generic import TemplateView
from management.mixins import SessionAuthenticationRequiredMixin, SessionOrgContextMixin
from django.shortcuts import redirect
from management.models import Organization

class DashboardView(SessionAuthenticationRequiredMixin, SessionOrgContextMixin, TemplateView):
    template_name = "management/pages/dashboard.html"

    def dispatch(self, *args, **kwargs):
        if len(self.get_context_data().get("organizations")) == 1:
            return redirect("management:organization", self.get_context_data().get("organizations")[0].id)
        return super(DashboardView, self).dispatch(*args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context

openalerts/management/views/organization.py
from django.views.generic.edit import UpdateView
from django.views.generic.detail import DetailView
from django.shortcuts import get_object_or_404, reverse
from django.utils import timezone
from django.conf import settings
from datetime import timedelta, datetime
from django import forms
from management.mixins import SessionAuthenticationRequiredMixin, SessionOrgContextMixin, OrgContextMixin
from management.models import Organization
from subscriptions.models import WebpushSubscription, EmailSubscription


class EditOrganizationView(
    SessionAuthenticationRequiredMixin, SessionOrgContextMixin, UpdateView
):
    template_name = "management/pages/edit_organization.html"
    model = Organization
    fields = ["name", "website", "description", "logo_url", "primary_color", "head_inject"]
    pk_url_kwarg = "org_id"

    def get_form(self, *args, **kwargs):
        form = super(EditOrganizationView, self).get_form(*args, **kwargs)
        form["primary_color"].field.widget.input_type = "color"
        return form
    
    def get_object(self):
        return get_object_or_404(Organization, id=self.kwargs["org_id"])

    def get_success_url(self):
        print(self.object.id)
        return reverse("management:organization", args=[self.object.id])

class OrganizationView(
    SessionAuthenticationRequiredMixin, SessionOrgContextMixin, DetailView
):
    template_name = "management/pages/organization.html"
    model = Organization
    pk_url_kwarg = "org_id"

    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)

        email_subscribers = EmailSubscription.objects.filter(organization=self.object)
        webpush_subscribers = WebpushSubscription.objects.filter(organization=self.object)

        data["subscribers"] = {
            "keys": str(["Email", "Web Alerts"]),
            "values": str([email_subscribers.count(),
                           webpush_subscribers.count()]),
            "count": email_subscribers.count() + webpush_subscribers.count(),
        }

        data["recent_alerts_count"] = self.object.alerts().filter(published__gt=timezone.now() - timedelta(days=1)).count()

        subscribers = list(email_subscribers) + list(webpush_subscribers)
        times = reversed([timezone.now() - timedelta(n) for n in range(90)]) # last 90 days

        data["subscribers_timeseries"] = {
            "label": "Currently Active Subscribers",
            "values": str([{
                "t": time.isoformat(),
                "y": len([subscription for subscription in subscribers if subscription.created <= time])
                # Deleted subscribers will not be shown in the chart, hence "current"
            } for time in times])
        }

        data["protocol_and_host"] = settings.PROTOCOL_AND_HOST

        return data

class OrganizationIntegrationsView(SessionAuthenticationRequiredMixin, SessionOrgContextMixin, DetailView):
    template_name = "management/pages/integrations.html"
    model = Organization
    pk_url_kwarg = "org_id"

    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)
        data["protocol_and_host"] = settings.PROTOCOL_AND_HOST
        return data

openalerts/management/views/sources.py
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic.base import ContextMixin
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django import forms
from django.core.paginator import Paginator
from management.mixins import (
    SessionAuthenticationRequiredMixin,
    SessionOrgContextMixin,
    OrgContextMixin,
)
from management.models import Organization
from alerts.models import Source, Channel


class SourceListView(
    SessionAuthenticationRequiredMixin, SessionOrgContextMixin, OrgContextMixin, DetailView
):
    template_name = "management/pages/source_list.html"
    model = Channel
    pk_url_kwarg = "channel_id"


class CreateSourceView(
    SessionAuthenticationRequiredMixin,
    SessionOrgContextMixin,
    OrgContextMixin,
    CreateView,
):
    template_name = "management/pages/edit_source.html"
    model = Source
    fields = ["source", "human_readable_identifier"]

    def get_form(self, *args, **kwargs):
        form = super(CreateSourceView, self).get_form(*args, **kwargs)
        form.fields['human_readable_identifier'].label = "Username or handle"
        form.fields['human_readable_identifier'].widget = forms.TextInput()
        return form

    def get_context_data(self, **kwargs):
        context = super(CreateSourceView, self).get_context_data(**kwargs)
        context.update(dict(channel=Channel.objects.get(id=self.kwargs["channel_id"])))
        return context

    def form_valid(self, form):
        form.instance.channel = self.get_context_data()["channel"]
        return super(CreateSourceView, self).form_valid(form)

    def get_success_url(self, **kwargs):
        return reverse_lazy(
            "management:source_list",
            kwargs={
                "org_id": self.kwargs["org_id"],
                "channel_id": self.object.channel.id,
            },
        )


class DeleteSourceView(
    SessionAuthenticationRequiredMixin,
    SessionOrgContextMixin,
    OrgContextMixin,
    DeleteView,
):
    template_name = "management/pages/delete_source.html"
    model = Source

    def get_success_url(self, **kwargs):
        return reverse_lazy(
            "management:source_list",
            kwargs={
                "org_id": self.kwargs["org_id"],
                "channel_id": self.kwargs["channel_id"],
            },
        )

openalerts/management/templates/management/pages/channel.html
{% extends 'management/organization_base.html' %}

{% load paginator %}
{% load humanize %}

{% block subsection %}
/ {{object.name}}
{% endblock %}

{% block action %}
<form method="GET" class="is-inline is-limited-width">
    <input type="search" class="input" name="search" value="{{request.GET.search}}"
        placeholder="Search for an alert...">
</form>
<a href="{% url "management:edit_channel" org_id=organization.id pk=object.id %}">Manage Channel</a>
<a href="{% url "management:create_alert" org_id=organization.id%}?channel={{object.id}}">Publish Alert</a>
{% endblock %}

{% block content %}
<p class="has-text-grey">Showing {{total_alerts|intcomma}} alert{% if total_alerts != 1 %}s{% endif %}.</p>
<br>
{% for alert in page_obj %}
{% include 'management/includes/alert.html' %}
<hr>
{% empty %}
<div class="notification">No alerts to show. <a
        href="{% url 'management:create_alert' org_id=organization.id %}?channel={{object.id}}">Click here</a> to create
    a new alert.</div>
{% endfor %}
{% pagination page_obj url_parameters=url_parameters %}
{% endblock %}

openalerts/management/templates/management/pages/channel_list.html
{% extends 'management/organization_base.html' %}

{% block subsection %}
/ Channels
{% endblock %}

{% block action %}
<a href="{% url "management:create_channel" org_id=organization.id %}">Create Channel</a>
{% endblock %}

{% block content %}
<div class="columns is-multiline">
    {% for channel in organization.channel_set.all %}
    <div class="column is-4">
        {% url 'management:channel' organization.id channel.id as url %}
        {% include 'management/includes/channel.html' %}
    </div>
    {% empty %}
    <div class="notification">No channels have been created. <a
            href="{% url "management:create_channel" org_id=organization.id %}">Click here</a> to create one.
    </div>
    {% endfor %}
</div>
{% endblock %}

openalerts/management/templates/management/pages/channels.html
{% extends 'management/organization_base.html' %}

{% block content %}
<div class="columns is-multiline">
    {% for channel in organization.channel_set.all %}
    <div class="column is-4">
        {% url 'management:channel' organization.id channel.id as url %}
        {% include 'alerts/includes/channel.html '%}
    </div>
    {% endfor %}
</div>
{% endblock %}

openalerts/management/templates/management/pages/delete_alert.html
{% extends 'management/organization_base.html' %}

{% load bulma_tags %}

{% block subsection %}
/ Delete Alert
{% endblock %}

{% block content %}
{% with alert=object %}
{% include 'management/includes/alert.html' %}
{% endwith %}
<div class="columns">
    <div class="column is-4">
        <div class="has-text-danger">Are you sure you want to delete this alert? This action cannot be undone.</div>
        <br>
        <form method="POST">
            {{form}}
            {% csrf_token %}
            <button type="submit" class="button is-danger">Delete</button>
        </form>
    </div>
</div>
{% endblock %}

openalerts/management/templates/management/pages/delete_channel.html
{% extends 'management/organization_base.html' %}

{% load bulma_tags %}

{% block subsection %}
/ Channels / Delete
{% endblock %}

{% block content %}
<div class="columns">
    <div class="column is-4">
        {% with channel=object %}
        {% include 'management/includes/channel.html' %}
        {% endwith %}
        <div class="has-text-danger">Are you sure you want to delete this channel and all of its alerts? This action
            cannot be undone.</div>
        <br>
        <form method="POST">
            {{form}}
            {% csrf_token %}
            <button type="submit" class="button is-danger">Delete</button>
        </form>
    </div>
</div>
{% endblock %}

openalerts/management/templates/management/pages/delete_source.html
{% extends 'management/organization_base.html' %}

{% load bulma_tags %}

{% block subsection %}
/ Channels / Delete
{% endblock %}

{% block content %}
<div class="columns">
    <div class="column is-4">
        <p>Please note that because sources are links between a channel and an external input, it is not possible to
            edit them. Instead, to change a source, we recommend that you delete it and create it anew.</p>
        <hr>
        {% with source=object %}
        {% include 'management/includes/source.html' %}
        {% endwith %}
        <div class="has-text-danger">Are you sure you want to delete this source? Its alerts will not be deleted.</div>
        <br>
        <form method="POST">
            {{form}}
            {% csrf_token %}
            <button type="submit" class="button is-danger">Delete</button>
        </form>
    </div>
</div>
{% endblock %}

openalerts/management/templates/management/pages/edit_alert.html
{% extends 'management/organization_base.html' %}

{% load bulma_tags %}

{% block subsection %}
/ Publish Alert
{% endblock %}

{% block content %}
<div class="columns">
    <div class="column is-4">
        <form method="POST">
            {% if view.edit %}
            <div class="notification">
                {{object.content}}
            </div>
            {% endif %}
            {{form|bulma}}
            {% csrf_token %}
            <br>
            <button type="submit" class="button is-link">Publish</button>
            {% if object %}
            <a href="{% url 'management:delete_alert' org_id=organization.id pk=object.id %}"
                class="button is-danger is-outlined">Delete</a>
            {% endif %}
        </form>
        <hr>
        <p class="has-text-grey">
            Please note that only an alert's URL is editable after it is published. If there is an error in the content
            of an alert, we recommend deleting the alert and publishing a correction.
        </p>
    </div>
</div>
{% endblock %}

openalerts/management/templates/management/pages/edit_channel.html
{% extends 'management/organization_base.html' %}

{% load bulma_tags %}

{% block subsection %}
/ Channels / {% if object %}Manage{% else %}Create{% endif %}
{% endblock %}

{% block action %}{% if object %}<a href="{% url "management:source_list" org_id=organization.id channel_id=object.id %}">Manage Sources</a>{% endif %}{% endblock %}

{% block content %}
<div class="columns">
    <div class="column is-4">
        <form method="POST">
            {{form|bulma}}
            {% csrf_token %}
            <br>
            <button type="submit" class="button is-link">Save</button>
            {% if object %}
            <a href="{% url 'management:delete_channel' org_id=organization.id pk=object.id %}"
                class="button is-danger is-outlined">Delete</a>
            {% endif %}
        </form>
    </div>
</div>
{% endblock %}

openalerts/management/templates/management/pages/edit_organization.html
{% extends 'management/organization_base.html' %}

{% load bulma_tags %}

{% block subsection %}
/ Configure
{% endblock %}

{% block content %}
<div class="columns">
    <form class="form column is-4" method="POST">
        {% csrf_token %}
        {{form|bulma}}
        <button type="submit" class="button is-outlined is-link">Save</button>
    </form>
</div>
{% endblock %}

openalerts/management/templates/management/pages/edit_source.html
{% extends 'management/organization_base.html' %}

{% load bulma_tags %}

{% block subsection %}
/ Channels / Edit
{% endblock %}

{% block content %}
{% if object %}
<h1 class="is-size-4">Edit Source</h1>
{% else %}
<h1 class="is-size-4">Create Source</h1>
{% endif %}
<br>
<div class="columns">
    <div class="column is-4">
        <form method="POST">
            {{form|bulma}}
            {% csrf_token %}
            <br>
            <button type="submit" class="button is-link">Save</button>
            {% if object %}
            <a href="{% url 'management:delete_channel' org_id=organization.id pk=object.id %}"
                class="button is-danger is-outlined">Delete</a>
            {% endif %}
        </form>
    </div>
</div>
{% endblock %}

openalerts/management/templates/management/pages/login.html
{% extends 'management/base.html' %}

{% block content %}
<div class="notification is-warning">
    <h3 class="title is-size-3">Please Log In</h3>
    <p>To view the OpenAlerts management dashboard for your organization, you must first log in with PressPass.</p>
    <p>If you aren't a member of an organization or think you're here by mistake, <a href="/">click here</a>.</p>
    <br>
    <a class="button is-link" href="{% url 'auth:begin' 'presspass' %}">Log In With PressPass</a>
</div>
{% endblock %}

openalerts/management/templates/management/pages/organization.html
{% extends 'management/organization_base.html' %}

{% load humanize %}
{% load static %}

{% block action %}
<a href="{% url 'management:create_alert' org_id=organization.id %}">Publish New Alert</a>
<a href="{% url 'management:edit_organization' org_id=organization.id %}">Configure Organization</a>
<a href="{% url 'management:integrations' org_id=organization.id %}">Integrations</a>
{% endblock %}

{% block content %}
<script src="https://cdn.jsdelivr.net/npm/chart.js@2.9.3/dist/Chart.bundle.min.js" integrity="sha256-TQq84xX6vkwR0Qs1qH5ADkP+MvH0W+9E7TdHJsoIQiM=" crossorigin="anonymous"></script>
<script src="{% static 'management/js/palette.js' %}"></script>

{% if recent_alerts_count > 4 %}
<div class="notification is-warning">
    <h4 class="title is-size-4 is-marginless has-text-weight-normal">Too Many Alerts</h4>
    <p>OpenAlerts strongly recommends that organizations publish no more than four alerts in any given twenty-four hour period to prevent audience burnout and maximize engagement.</p>
</div>
{% endif %}

<div class="columns">
    <div class="column">
        <div class="box">
            <p class="heading">Total Subscribers</p>
            <h3 class="title is-size-3 has-text-weight-light">{{organization.subscriber_count|intcomma}}</h3>
        </div>
    </div>
    <div class="column">
        <div class="box">
            <p class="heading">Latest Alert</p>
            <h3 class="title is-size-3 has-text-weight-light">{{organization.alerts.0.published|naturaltime}}</h3>
        </div>
    </div>
    <div class="column">
        <div class="box">
            <p class="heading">Alerts Today</p>
            <h3 class="title is-size-3 {% if recent_alerts_count > 4 %}has-text-danger{% endif %} has-text-weight-light">{{recent_alerts_count|intcomma}}</h3>
        </div>
    </div>
</div>

<div class="columns">
    <div class="column is-8" style="height: 400px">
        <h4 class="is-size-6 title has-text-centered">Total Subscribers</h4>
        {% include 'management/includes/timeseries_chart.html' with name="subscribers_timeseries" label=subscribers_timeseries.label values=subscribers_timeseries.values %}
        <p class="has-text-grey is-italic"><small>Due to privacy concerns, data from unsubscribed users is not retained, and unsubscribed users will not affect this chart's totals.</small></p>
    </div>
    <div class="column is-4">
        <h4 class="is-size-6 title has-text-centered">Subscriber Breakdown</h4>
        {% include 'management/includes/doughnut_chart.html' with name="subscribers" keys=subscribers.keys values=subscribers.values count=subscribers.count %}
    </div>
</div>
{% endblock %} 

openalerts/management/templates/management/pages/source_list.html
{% extends 'management/organization_base.html' %}

{% block subsection %}
/ {{channel.name}} / Sources
{% endblock %}

{% block action %}
<a href="{% url 'management:create_source' org_id=organization.id channel_id=object.id %}">Create Source</a>
{% endblock %}

{% block content %}
<div class="columns is-multiline">
    {% for source in channel.source_set.all %}
    <div class="column is-4">
        {% url 'management:delete_source' organization.id object.id source.id as url %}
        {% include 'management/includes/source.html' %}
    </div>
    {% empty %}
    <div class="notification">No sources have been created. <a
            href="{% url 'management:create_source' org_id=organization.id channel_id=channel.id %}">Click here</a> to
        create one.
    </div>
    {% endfor %}
</div>
{% endblock %}